# Generated by Django 4.2.6 on 2023-10-26 06:24

import ckeditor.fields
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': 'Data Kategori'},
        ),
        migrations.AlterModelOptions(
            name='kontak',
            options={'verbose_name_plural': 'Data Kontak'},
        ),
        migrations.AlterModelOptions(
            name='produk',
            options={'verbose_name_plural': 'Data Produk'},
        ),
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name_plural': 'Data Profil'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name_plural': 'Data Slide'},
        ),
        migrations.AlterModelOptions(
            name='statis',
            options={'verbose_name_plural': 'Data Statis'},
        ),
        migrations.AlterField(
            model_name='kategori',
            name='banner_dua',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[575, 200], upload_to='gambar/banner', verbose_name='Gambar Banner Dua (575 x 200 pixel)'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='banner_satu',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[575, 200], upload_to='gambar/banner', verbose_name='Gambar Banner Satu (575 x 200 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/banner', verbose_name='Gambar (270 x 250 pixe)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_dua',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/banner', verbose_name='Gambar Dua (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_empat',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/banner', verbose_name='Gambar Empat (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_lima',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/banner', verbose_name='Gambar Lima (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_satu',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/banner', verbose_name='Gambar Satu (270 x 250 pixe)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_tiga',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/banner', verbose_name='Gambar Tiga (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='keterangan',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='gambar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, quality=80, scale=None, size=[1920, 1200], upload_to='gambar/banner', verbose_name='Gambar (1920 x 1200 pixel)'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='keterangan',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='gambar_slide',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[475, 880], upload_to='gambar/banner', verbose_name='Gambar Slide(475 x 880 pixel)'),
        ),
    ]
